#pragma once

#include <string>

namespace nabto {
namespace test {

// This is Nabto root CA1
const std::string nabtoRootCA1 = R"(-----BEGIN CERTIFICATE-----
MIIB2TCCAX6gAwIBAgIUUmg861HL9RvPvsLpRPtz4sAlLj0wCgYIKoZIzj0EAwIw
NzELMAkGA1UEBhMCREsxDjAMBgNVBAoMBU5hYnRvMRgwFgYDVQQDDA9OYWJ0byBS
b290IENBIDEwHhcNMjAxMDAyMjA1MzAzWhcNMjMxMDAyMjA1MzAzWjA5MQswCQYD
VQQGEwJESzEOMAwGA1UECgwFTmFidG8xGjAYBgNVBAMMEU5hYnRvIFNlcnZlciBD
QSAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELHA41RHIH5Wtoa4FVjL8GRO3
QeiCFCnQLigy1w/NFc9Tu8b77exHkVUQX5/TXXg96etIQr0FRsXriCKxNOFSyqNm
MGQwHQYDVR0OBBYEFE3qi2c0kMB4pIPTzQtYJLDTegDLMB8GA1UdIwQYMBaAFDTV
WO6JLN0TW6zyW51IQzFKZxuvMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/
BAQDAgGGMAoGCCqGSM49BAMCA0kAMEYCIQDvemE0MvLMaFyPpP/GJ0aiTdxfjOUq
zh41kuKNbT8VFwIhAOl8mF7nslw+4YIp7Wsw5vl74YRcw/j0CYCe3iFMkz2F
-----END CERTIFICATE-----
)";

// Test private key
// certificate-authority/test/test-intermediate/test-keys/localhost-multi.nabto.net/localhost-multi.nabto.net.key
const std::string privateKey = R"(-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIMdRmzNQrp+WRBwt9WXxZQSqe+ZQEtEuAQRZqwuB8nX9oAoGCCqGSM49
AwEHoUQDQgAEShTBGm7dCj1JBJHF82g53jeaz2afIlktXYqHy1FcUzTeV7c9+Lk7
W0AlwL/AcMp+rBJbjFaCdG7NYjNKhK0Atw==
-----END EC PRIVATE KEY-----
)";

// OK Test certificate for localhost-multi.nabto.net
// certificate-authority/test/test-intermediate/test-keys/localhost-multi.nabto.net/localhost-multi.nabto.net.crt
const std::string localhostMultiNabtoNetCert = R"(-----BEGIN CERTIFICATE-----
MIIBdDCCARkCFEh95/4m0eBaOUjPKXnVI6avwCB8MAoGCCqGSM49BAMCMDgxCzAJ
BgNVBAYTAkRLMQ0wCwYDVQQKDARUZXN0MRowGAYDVQQDDBFUZXN0IEludGVybWVk
aWF0ZTAeFw0yMjEyMTYwOTM1NDFaFw0yNTAyMjMwOTM1NDFaMEAxCzAJBgNVBAYT
AkRLMQ0wCwYDVQQKDARUZXN0MSIwIAYDVQQDDBlsb2NhbGhvc3QtbXVsdGkubmFi
dG8ubmV0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEShTBGm7dCj1JBJHF82g5
3jeaz2afIlktXYqHy1FcUzTeV7c9+Lk7W0AlwL/AcMp+rBJbjFaCdG7NYjNKhK0A
tzAKBggqhkjOPQQDAgNJADBGAiEAr5TClZsLSFxXSWVw5vEliwx8db2N2HuhbhOy
ncBfyMcCIQDzystIG+pButGthP96QU/u+cneGFDWeov7BR6sXF8Zsw==
-----END CERTIFICATE-----
)";

// certificate-authority/test/test-intermediate/test-keys/localhost-multi.nabto.net/expired-localhost-multi.nabto.net.crt
const std::string expiredLocalhostMultiNabtoNetCert = R"(-----BEGIN CERTIFICATE-----
MIIBczCCARkCFEb4FA2SEN1Ywwy0/0eFlf9094n3MAoGCCqGSM49BAMCMDgxCzAJ
BgNVBAYTAkRLMQ0wCwYDVQQKDARUZXN0MRowGAYDVQQDDBFUZXN0IEludGVybWVk
aWF0ZTAeFw0xOTAxMDExMDExMTJaFw0yMTAxMDExMDExMTJaMEAxCzAJBgNVBAYT
AkRLMQ0wCwYDVQQKDARUZXN0MSIwIAYDVQQDDBlsb2NhbGhvc3QtbXVsdGkubmFi
dG8ubmV0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEShTBGm7dCj1JBJHF82g5
3jeaz2afIlktXYqHy1FcUzTeV7c9+Lk7W0AlwL/AcMp+rBJbjFaCdG7NYjNKhK0A
tzAKBggqhkjOPQQDAgNIADBFAiEA+X03QbZOlAe8NvdJ1GEQxks+AFklVFCTp3zf
REGk+DMCICswVay3ZoylLfB7pO0Whg0JkxkDZx8qU94lc53H2D/n
-----END CERTIFICATE-----
)";

// certificate-authority/test/test-root/certs/test_intermediate.crt
const std::string testIntermediateCert = R"(-----BEGIN CERTIFICATE-----
MIIB0DCCAXagAwIBAgIUTO6HGwG4blVBeCdFjPLmOPhDNZswCgYIKoZIzj0EAwIw
MDELMAkGA1UEBhMCREsxDTALBgNVBAoMBFRlc3QxEjAQBgNVBAMMCVRlc3QgUm9v
dDAeFw0yMjEyMTYwOTMzNDFaFw0yNTEyMTUwOTMzNDFaMDgxCzAJBgNVBAYTAkRL
MQ0wCwYDVQQKDARUZXN0MRowGAYDVQQDDBFUZXN0IEludGVybWVkaWF0ZTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABB/ceDZO2PN7gT5TuggLGXbS96jJ/orkTgXX
MsQ8E+aImQDyKhHC9cWhwclKso7gyQIeAcqiyMrpDBnqKgktjfijZjBkMB0GA1Ud
DgQWBBT3JkWHFo2+s0tr+kiy+00penDxDTAfBgNVHSMEGDAWgBRyog+DI9u8+S/g
kI1n8CXfJdO8jjASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAK
BggqhkjOPQQDAgNIADBFAiB1ztkOk+Et0l48frlOh20n37lCa3znerGtFOO8mE0B
eAIhAK9HBLk5AnDlmYQRKyoyJEXpmH8U5CKOdb8Fx79S4V9o
-----END CERTIFICATE-----
)";

// certificate-authority/test/test-root/certs/test_root.crt
const std::string testRootCa = R"(-----BEGIN CERTIFICATE-----
MIIBpTCCAUqgAwIBAgIUev5miQGPmjlHmisQJ5iYiq+Lf0kwCgYIKoZIzj0EAwIw
MDELMAkGA1UEBhMCREsxDTALBgNVBAoMBFRlc3QxEjAQBgNVBAMMCVRlc3QgUm9v
dDAeFw0yMDA2MjAwMDAwMDBaFw00OTEyMzEyMzU5NTlaMDAxCzAJBgNVBAYTAkRL
MQ0wCwYDVQQKDARUZXN0MRIwEAYDVQQDDAlUZXN0IFJvb3QwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAATWs9bVLhO8o+42UrDFZocbMjvt20ODDwjxjC5/lSKo8KU6
yPcBsI6IMg+CfMfQpza7V5m9c/mHXw1r8iiOrizio0IwQDAdBgNVHQ4EFgQUcqIP
gyPbvPkv4JCNZ/Al3yXTvI4wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwCgYIKoZIzj0EAwIDSQAwRgIhAKjXktlBZjxURdyDvlvPUn73cNz8MOTs7wl3
ogsvei0AAiEA4r6s8iI6b37agG6zXsPKXwjTw3jS4acs1feiZ4Vo1NE=
-----END CERTIFICATE-----
)";

}
}
