#ifndef _NM_POLICIES_DEFINES_H_
#define _NM_POLICIES_DEFINES_H_

enum nm_policies_effect {
    NM_POLICIES_EFFECT_ALLOW,
    NM_POLICIES_EFFECT_DENY,
    NM_POLICIES_EFFECT_NO_MATCH,
    NM_POLICIES_EFFECT_ERROR
};



#endif
