#ifndef _NABTO_DEVICE_CONFIG_H_
#define _NABTO_DEVICE_CONFIG_H_

#ifndef NABTO_DEVICE_LOG_STD_OUT_CALLBACK
#define NABTO_DEVICE_LOG_STD_OUT_CALLBACK 1
#endif

#ifndef NABTO_DEVICE_MDNS_ENABLED
#define NABTO_DEVICE_MDNS_ENABLED 1
#endif

#endif
