#ifndef _NC_DEVICE_DEFINES_H_
#define _NC_DEVICE_DEFINES_H_

enum nc_device_event {
    NC_DEVICE_EVENT_ATTACHED,
    NC_DEVICE_EVENT_DETACHED,
    NC_DEVICE_EVENT_CLOSED,
    NC_DEVICE_EVENT_INVALID_FINGERPRINT,
    NC_DEVICE_EVENT_INVALID_PRODUCT_ID,
    NC_DEVICE_EVENT_INVALID_DEVICE_ID
};

#endif
