#ifndef NP_ERROR_CODE_H
#define NP_ERROR_CODE_H

// TODO use categories.

typedef enum {
    NABTO_EC_OK = 0,
    NABTO_EC_FAILED,
    NABTO_EC_UDP_SOCKET_CREATION_ERROR,
    NABTO_EC_UDP_SOCKET_ERROR,
    NABTO_EC_INVALID_SOCKET,
    NABTO_EC_FAILED_TO_SEND_PACKET,
    NABTO_EC_MALFORMED_PACKET,
    NABTO_EC_OUT_OF_CHANNELS,
    NABTO_EC_OUT_OF_CONNECTIONS,
    NABTO_EC_INVALID_CHANNEL,
    NABTO_EC_INVALID_CONNECTION_ID,
    NABTO_EC_INVALID_PACKET_TYPE,
    NABTO_EC_INSUFFICIENT_BUFFER_ALLOCATION,
    NABTO_EC_ALPN_FAILED,
    NABTO_EC_INVALID_PEER_FINGERPRINT,
    NABTO_EC_CONNECTION_CLOSING,
    NABTO_EC_KEEP_ALIVE_TIMEOUT,
    NABTO_EC_SEND_IN_PROGRESS,
    NABTO_EC_API_FUTURE_NOT_READY,
    NABTO_EC_NO_VALID_ENDPOINTS,
    NABTO_EC_OPERATION_IN_PROGRESS,
    NABTO_EC_ABORTED,
    NABTO_EC_STREAM_CLOSED,
    NABTO_EC_STREAM_EOF,
    NABTO_EC_RESOURCE_EXISTS,
    NABTO_EC_NO_SUCH_RESOURCE,
    NABTO_EC_RESOURCE_IN_USE,
    NABTO_EC_OUT_OF_MEMORY,
    NABTO_EC_NOT_IMPLEMENTED,
    NABTO_EC_IAM_INVALID_POLICY
} np_error_code;

const char* np_error_code_to_string(np_error_code ec);

#endif
