name: Build and test the software on MbedTLS 3

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    name: Build
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Change MbedTLS version
        run: cd 3rdparty/mbedtls/mbedtls && git fetch && git checkout v3.2.1

      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && cmake -DDEVICE_BUILD_TESTS=ON -DDEVICE_MBEDTLS_2=OFF -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts ..

      - name: Build
        run: cmake --build build-dir --parallel

      - name: Install
        run: cmake --build build-dir --target install

      - name: test
        run: ./artifacts/bin/embedded_unit_test
