name: Build Release Artifacts

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-12]
        include:
          - os: windows-2022
            exe_postfix: .exe
            friendly_name: windows
          - os: ubuntu-20.04
            exe_postfix:
            friendly_name: linux
          - os: macos-12
            exe_postfix:
            friendly_name: macos
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -DDEVICE_STATIC_LINK_VCRUNTIME=ON ..

      - name: Build
        run: cmake --build build-dir --parallel

      - name: Install
        run: cmake --build build-dir --target install

      - name: Prepate assets
        run: |
          mv ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device${{ matrix.exe_postfix }} ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
          mv ${{ github.workspace }}/artifacts/bin/thermostat_device${{ matrix.exe_postfix }} ${{ github.workspace }}/artifacts/bin/thermostat_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}

      - name: Upload artifacts to github actions workspace artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          # omit name and upload to defaults artifacts archive called artifact.
          path: |
            ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
            ${{ github.workspace }}/artifacts/bin/thermostat_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
          if-no-files-found: error

  upload-artifacts:
    strategy:
      matrix:
        binary: [tcp_tunnel_device_linux, tcp_tunnel_device_macos, tcp_tunnel_device_windows.exe, thermostat_device_linux, thermostat_device_macos, thermostat_device_windows.exe]
    name: Release Assets
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      # give access to upload an artifacts to gh releases
      contents: write

    if: github.event_name == 'release'
    steps:
      - name:  download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: list files
        run: ls -R
      - name: Upload Source Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifact/${{matrix.binary}}
          asset_name: ${{matrix.binary}}
          asset_content_type: application/octet-stream
