name: Build shared library

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    timeout-minutes: 30
    name: Build
    runs-on: ${{matrix.workflow.os}}
    strategy:
      matrix:
        workflow:
          - os: windows-2022
            name: "windows_shared_library"
          - os: ubuntu-24.04
            name: "linux_shared_library"
          - os: macos-15
            name: "mac_arm64_shared_library"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Temporarily ping CMake version to 3.31 (see #47)
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Build
        run: cmake --workflow --preset ${{ matrix.workflow.name }}
