name: Build Release Artifacts

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-12]
        include:
          - os: windows-2022
            exe_postfix: .exe
            friendly_name: windows
            build_command: cmake --build build-dir --parallel --target install --config Release
          - os: ubuntu-20.04
            exe_postfix:
            friendly_name: linux_x86_64
            build_command: cmake --build build-dir --parallel --target install
          - os: macos-12
            exe_postfix:
            friendly_name: macos
            # 2024-01-05: Sometimes mac fails on github actions when doing builds so we use make without parallellism directly, since we hope that fixes the unknown problem.
            build_command: cd build-dir && make -j 1 install
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -DDEVICE_STATIC_LINK_VCRUNTIME=ON ..

      - name: Build
        run: ${{matrix.build_command}}

      - name: Prepate assets
        run: |
          mv ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device${{ matrix.exe_postfix }} ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
          mv ${{ github.workspace }}/artifacts/bin/thermostat_device${{ matrix.exe_postfix }} ${{ github.workspace }}/artifacts/bin/thermostat_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}

      - name: Upload artifacts to github actions workspace artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          # omit name and upload to defaults artifacts archive called artifact.
          path: |
            ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
            ${{ github.workspace }}/artifacts/bin/thermostat_device_${{matrix.friendly_name}}${{ matrix.exe_postfix }}
            ${{ github.workspace }}/artifacts/bin
          if-no-files-found: error

  build-linux-arm:
    timeout-minutes: 20
    strategy:
      matrix:
        arch: [armv6, armhf, aarch64]
        include:
          - arch: armv6
            compiler: arm-linux-gnueabihf
            toolchain: https://nabto-build-assets.s3.eu-west-1.amazonaws.com/toolchains/cross-gcc-9.4.0-pi_0-1.tar.gz
          - arch: armhf
            compiler: arm-linux-gnueabihf
            toolchain: https://nabto-build-assets.s3.eu-west-1.amazonaws.com/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
          - arch: aarch64
            compiler: aarch64-linux-gnu
            toolchain: https://nabto-build-assets.s3.eu-west-1.amazonaws.com/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Get required packages
      run: sudo apt install libarchive-tools

    - name: Create directory
      run: mkdir toolchain

    - name: Get toolchain
      working-directory: toolchain
      run: curl -sSL ${{ matrix.toolchain }}  | bsdtar -xf - --strip-components=1

    - name: Configure CMake
      env:
        CC: ${{github.workspace}}/toolchain/bin/${{ matrix.compiler }}-gcc
        CXX: ${{github.workspace}}/toolchain/bin/${{ matrix.compiler }}-g++
      run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel

    - name: Install
      run: cmake --build ${{github.workspace}}/build --target install

    - name: Print architecture
      run: file ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device

    - name: Prepate assets
      run: |
        mv ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_linux_${{matrix.arch}}
        mv ${{ github.workspace }}/artifacts/bin/thermostat_device ${{ github.workspace }}/artifacts/bin/thermostat_device_linux_${{matrix.arch}}


    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        path: |
          ${{ github.workspace }}/artifacts/bin/tcp_tunnel_device_linux_${{matrix.arch}}
          ${{ github.workspace }}/artifacts/bin/thermostat_device_linux_${{matrix.arch}}
        if-no-files-found: error


  upload-artifacts:
    timeout-minutes: 20
    strategy:
      matrix:
        binary: [tcp_tunnel_device, thermostat_device]
        suffix: [linux_x86_64, linux_armv6, linux_armhf, linux_aarch64, windows.exe, macos]
    name: Release Assets
    needs: [ build, build-linux-arm ]
    runs-on: ubuntu-22.04
    permissions:
      # give access to upload an artifacts to gh releases
      contents: write

    if: github.event_name == 'release'
    steps:
      - name:  download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: list files
        run: ls -R
      - name: Upload Source Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifact/${{matrix.binary}}_${{matrix.suffix}}
          asset_name: ${{matrix.binary}}_${{matrix.suffix}}
          asset_content_type: application/octet-stream
