name: Build And Test Linux Mac Windows

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    timeout-minutes: 20
    name: Build
    runs-on: ${{matrix.workflow.os}}
    strategy:
      matrix:
        workflow:
          - os: ubuntu-24.04
            name: "linux_fetchcontent"
          - os: ubuntu-24.04
            name: "linux_vcpkg"
          - os: ubuntu-24.04
            name: "linux_vcpkg_dtls_client_only"

          - os: windows-2022
            name: "windows_vcpkg_static"

          - os: macos-15
            name: mac_vcpkg_x86_64
          - os: macos-15
            name: mac_fetchcontent_universal

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Temporarily ping CMake version to 3.31 (see #47)
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - if: matrix.workflow.os == 'ubuntu-24.04'
        name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - if: matrix.workflow.os == 'macos-15'
        name: Install Ninja
        run: brew install ninja

      - name: Build
        run: cmake --workflow --preset ${{ matrix.workflow.name }}

      - if: matrix.workflow.os == 'windows-2022'
        name: Test run
        run: |
          netsh advfirewall firewall add rule name="embedded_unit_test" dir=in action=allow program="${{ github.workspace }}\build\${{ matrix.workflow.name }}\install\bin\embedded_unit_test.exe" enable=yes
          ${{ github.workspace }}\build\${{ matrix.workflow.name }}\install\bin\embedded_unit_test.exe -l test_suite --detect_memory_leaks=0

      - if: matrix.workflow.os != 'windows-2022'
        name: Test run
        run: ${{ github.workspace }}/build/${{ matrix.workflow.name }}/install/bin/embedded_unit_test -l test_suite --detect_memory_leaks=0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_and_test_${{ matrix.workflow.name }}_${{ matrix.workflow.os }}
          path: ${{ github.workspace }}/artifacts
          if-no-files-found: warn
          overwrite: true
