name: build and test ubuntu 16.04
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -DDEVICE_BUILD_TESTS=ON ..

      - name: Build
        run: cmake --build build-dir --parallel

      - name: Install
        run: cmake --build build-dir --target Install

      - name: Test run
        run: ${{ github.workspace }}/artifacts/bin/embedded_unit_test -l test_suite --detect_memory_leaks=0
