name: Build windows nabto_device.dll

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    timeout-minutes: 30
    name: Build
    runs-on: ${{matrix.workflow.os}}
    strategy:
      matrix:
        workflow:
          - os: windows-2022
            name: "windows_nabto_device_dll"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Temporarily ping CMake version to 3.31 (see #47)
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Build
        run: cmake --workflow --preset ${{ matrix.workflow.name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_and_test_${{ matrix.workflow.name }}_${{ matrix.workflow.os }}
          path: ${{ github.workspace }}/artifacts
          if-no-files-found: warn
          overwrite: true
