name: build and test ubuntu 22.04
on:
  push:

jobs:
  build-and-test:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -DDEVICE_BUILD_TESTS=ON ..

      - name: Build
        run: cd build-dir && make -j 4

      - name: Install
        run: cd build-dir && make install

      - name: Test run
        run: ${{ github.workspace }}/artifacts/bin/embedded_unit_test -l test_suite --detect_memory_leaks=0
