name: Check code

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    timeout-minutes: 20
    name: Build
    runs-on: ${{matrix.workflow.os}}
    strategy:
      matrix:
        workflow:
          - os: ubuntu-24.04
          - os: macos-15
    steps:
      - if: matrix.workflow.os == 'ubuntu-24.04'
        name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build build-essential cmake git

      - if: matrix.workflow.os == 'macos-15'
        name: Install Ninja
        run: brew install ninja
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build werror
        run: cmake --workflow --preset werror
      - name: Build clang tidy
        run: cmake --workflow --preset clang_tidy
