name: Source Release
on:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: nabto-embedded-sdk
          fetch-depth: 0
      - name: Generate src/core/nc_version.c
        run: mkdir builddir && cd builddir && cmake ${{ github.workspace }}/nabto-embedded-sdk && make GENERATE_VERSION

      - name: Create zip
        run: mkdir -p ${{ github.workspace }}/artifacts && zip -r ${{ github.workspace }}/artifacts/nabto-embedded-sdk.zip nabto-embedded-sdk -x '*.git*' '*artifacts*'

      - uses: actions/upload-artifact@v3
        with:
          name: source
          path: ${{ github.workspace }}/artifacts/nabto-embedded-sdk.zip

  release-assets:
    name: Release Assets
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      # give access to upload an artifacts to gh releases
      contents: write

    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./
      - name: list files
        run: ls -R
      - name: Upload Source Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./source/nabto-embedded-sdk.zip
          asset_name: nabto-embedded-sdk.zip
          asset_content_type: application/zip
