name: Test Version Override

on:
  push:
  pull_request:

jobs:
  test-version-override:
    timeout-minutes: 30
    name: Test Version Override - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            preset_name: linux_shared_library
          - os: windows-2022
            preset_name: windows_shared_library
          - os: macos-15
            preset_name: mac_arm64_shared_library

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Install Ninja (Ubuntu)
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Install Ninja (macOS)
        if: matrix.os == 'macos-15'
        run: brew install ninja

      - name: Configure CMake with custom version
        run: cmake --preset ${{ matrix.preset_name }} -DNABTO_DEVICE_VERSION="1.2.3-test"

      - name: Build shared library
        run: cmake --build --preset ${{ matrix.preset_name }} --target install
