name: Use MbedTLS as a Library

on:
  push:
  release:
    types: [ published ]

jobs:
  build-and-test:
    timeout-minutes: 20
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: build
      run: mkdir build && cd build && ../test/mbedtls_as_library/build.sh
